FROM node:12-alpine3.14
WORKDIR /app
# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force
RUN npm install -g pm2
COPY . .
CMD pm2 start src/index.js
EXPOSE 3000
